const express=require('express');
const cors=require('cors');
const store=require('./backend/store');
const {sign,read,requireUser,requireAdmin}=require('./backend/auth');
const app=express();
const PORT=process.env.PORT||3001;
const origins=(process.env.FRONTEND_ORIGIN||'https://bigode-bypass.onrender.com,http://localhost:3000').split(',').map(x=>x.trim());
app.disable('x-powered-by');
app.use((req,res,next)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','strict-origin-when-cross-origin');next()});
app.use(cors({origin:(origin,cb)=>!origin||origins.includes(origin)?cb(null,true):cb(new Error('Origem não permitida')),credentials:false}));
app.use(express.json({limit:'100kb'}));
const safe=fn=>async(req,res)=>{try{await fn(req,res)}catch(e){console.error(e);res.status(400).json({error:e.message||'Erro interno'})}};
app.get('/health',(req,res)=>res.json({ok:true,database:store.useDb()?'postgres':'memory'}));
app.get('/products',safe(async(req,res)=>res.json({products:await store.listProducts(false)})));
app.get('/products/:slug',safe(async(req,res)=>{const p=await store.getProduct(req.params.slug);if(!p||!p.active)return res.status(404).json({error:'Produto não encontrado'});res.json({product:p})}));
app.post('/auth/register',safe(async(req,res)=>{const user=await store.createUser(req.body);res.json({user,token:sign(user)})}));
app.post('/auth/login',safe(async(req,res)=>{const user=await store.authenticate(req.body.email,req.body.password);if(!user)return res.status(401).json({error:'E-mail ou senha inválidos'});res.json({user,token:sign(user)})}));
app.get('/auth/me',requireUser,safe(async(req,res)=>{const user=await store.getUser(req.session.sub);if(!user)return res.status(401).json({error:'Sessão inválida'});res.json({user})}));
app.post('/coupons/validate',safe(async(req,res)=>res.json(await store.validateCoupon(req.body.code,req.body.subtotal))));
app.post('/orders',safe(async(req,res)=>{const session=read(req);const user=session?await store.getUser(session.sub):null;const b=req.body;const order=await store.createOrder({userId:user?.id,customerName:b.customerName||user?.name,customerEmail:b.customerEmail||user?.email,cpf:b.cpf||user?.cpf,items:b.items,couponCode:b.couponCode,paymentMethod:b.paymentMethod||'pix'});res.json({order})}));
app.get('/orders',requireUser,safe(async(req,res)=>res.json({orders:await store.listOrders(req.session.sub)})));
app.get('/admin/dashboard',requireAdmin,safe(async(req,res)=>res.json(await store.dashboard())));
app.get('/admin/products',requireAdmin,safe(async(req,res)=>res.json({products:await store.listProducts(true)})));
app.post('/admin/products',requireAdmin,safe(async(req,res)=>res.json({product:await store.createProduct(req.body)})));
app.patch('/admin/products/:id',requireAdmin,safe(async(req,res)=>res.json({product:await store.updateProduct(req.params.id,req.body)})));
app.get('/admin/orders',requireAdmin,safe(async(req,res)=>res.json({orders:await store.listAllOrders()})));
app.patch('/admin/orders/:id',requireAdmin,safe(async(req,res)=>res.json({order:await store.updateOrder(req.params.id,req.body)})));
app.get('/admin/coupons',requireAdmin,safe(async(req,res)=>res.json({coupons:await store.listCoupons()})));
app.post('/admin/coupons',requireAdmin,safe(async(req,res)=>res.json({coupon:await store.createCoupon(req.body)})));
app.patch('/admin/coupons/:id',requireAdmin,safe(async(req,res)=>res.json({coupon:await store.updateCoupon(req.params.id,req.body)})));
app.use((req,res)=>res.status(404).json({error:'Rota não encontrada'}));
app.listen(PORT,()=>console.log('Bigode Bypass API online na porta '+PORT));