'use client';
import{useEffect,useState}from'react';
import{api,setToken}from'../../lib/api-client';
const money=v=>'R$ '+Number(v||0).toFixed(2).replace('.',',');
export default function Admin(){
 const[user,setUser]=useState(undefined),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[tab,setTab]=useState('overview'),[metrics,setMetrics]=useState({}),[products,setProducts]=useState([]),[orders,setOrders]=useState([]),[coupons,setCoupons]=useState([]),[msg,setMsg]=useState('');
 const load=async()=>{const me=await api('/auth/me');setUser(me.user);if(me.user.role!=='admin')return;const[d,p,o,c]=await Promise.all([api('/admin/dashboard'),api('/admin/products'),api('/admin/orders'),api('/admin/coupons')]);setMetrics(d);setProducts(p.products||[]);setOrders(o.orders||[]);setCoupons(c.coupons||[])};
 useEffect(()=>{load().catch(()=>setUser(null))},[]);
 const login=async e=>{e.preventDefault();try{const d=await api('/auth/login',{method:'POST',body:JSON.stringify({email,password})});setToken(d.token);await load()}catch(e){setMsg(e.message)}};
 const patchProduct=async(p,changes)=>{try{const d=await api('/admin/products/'+p.id,{method:'PATCH',body:JSON.stringify(changes)});setProducts(xs=>xs.map(x=>x.id===p.id?d.product:x));setMsg('Produto atualizado.')}catch(e){setMsg(e.message)}};
 const createCoupon=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{const d=await api('/admin/coupons',{method:'POST',body:JSON.stringify({code:f.get('code'),type:f.get('type'),value:Number(f.get('value')),maxUses:Number(f.get('maxUses'))||null})});setCoupons(x=>[d.coupon,...x]);e.currentTarget.reset();setMsg('Cupom criado.')}catch(e){setMsg(e.message)}};
 const status=async(o,s)=>{const d=await api('/admin/orders/'+o.id,{method:'PATCH',body:JSON.stringify({status:s})});setOrders(xs=>xs.map(x=>x.id===o.id?d.order:x));};
 if(user===undefined)return <main className="adminLogin"><p>Carregando...</p></main>;
 if(!user||user.role!=='admin')return <main className="adminLogin"><form onSubmit={login}><img src="/logo-bigode-bypass.png"/><h1>Administração</h1><input type="email" placeholder="E-mail" value={email} onChange={e=>setEmail(e.target.value)} required/><input type="password" placeholder="Senha" value={password} onChange={e=>setPassword(e.target.value)} required/>{msg&&<p>{msg}</p>}<button>Entrar</button><a href="/">← Voltar para a loja</a></form></main>;
 return <main className="adminPage"><aside><div className="adminBrand"><img src="/logo-bigode-bypass.png"/><div><h2>BIGODE</h2><small>BYPASS</small></div></div><small>ADMINISTRAÇÃO</small><button className={tab==='overview'?'active':''} onClick={()=>setTab('overview')}>▦ Visão geral</button><button className={tab==='products'?'active':''} onClick={()=>setTab('products')}>▣ Produtos</button><button className={tab==='orders'?'active':''} onClick={()=>setTab('orders')}>◫ Pedidos</button><button className={tab==='coupons'?'active':''} onClick={()=>setTab('coupons')}>◇ Cupons</button><a href="/">← Ver loja</a></aside><section><span>PAINEL ADMINISTRATIVO</span><h1>{tab==='overview'?'Visão geral':tab==='products'?'Produtos':tab==='orders'?'Pedidos':'Cupons'}</h1>{msg&&<p className="formMessage">{msg}</p>}
 {tab==='overview'&&<><div className="metrics"><div><small>Produtos</small><b>{metrics.products||0}</b></div><div><small>Pedidos</small><b>{metrics.orders||0}</b></div><div><small>Receita paga</small><b>{money(metrics.revenue)}</b></div><div><small>Pendentes</small><b>{metrics.pending||0}</b></div></div></>}
 {tab==='products'&&<div className="adminTable productsAdmin"><h2>Gerenciar produtos</h2>{products.map(p=><div className="adminProductRow" key={p.id}><b>{p.name}</b><label>Preço<input type="number" defaultValue={p.price} onBlur={e=>patchProduct(p,{price:Number(e.target.value)})}/></label><label>Estoque<input type="number" defaultValue={p.stock} onBlur={e=>patchProduct(p,{stock:Number(e.target.value)})}/></label><label className="switchLabel"><input type="checkbox" defaultChecked={p.active} onChange={e=>patchProduct(p,{active:e.target.checked})}/> Ativo</label><a href={'/produto?slug='+p.slug}>Ver</a></div>)}</div>}
 {tab==='orders'&&<div className="adminTable"><h2>Pedidos</h2>{orders.map(o=><div className="adminOrderRow" key={o.id}><b>#{o.id}</b><span>{o.customer_email}</span><span>{money(o.total)}</span><select value={o.status} onChange={e=>status(o,e.target.value)}><option value="pending">Pendente</option><option value="paid">Pago</option><option value="cancelled">Cancelado</option><option value="delivered">Entregue</option></select></div>)}{!orders.length&&<p>Nenhum pedido.</p>}</div>}
 {tab==='coupons'&&<><form className="couponAdmin" onSubmit={createCoupon}><input name="code" placeholder="Código" required/><select name="type"><option value="percent">Percentual</option><option value="fixed">Valor fixo</option></select><input name="value" type="number" step="0.01" placeholder="Valor" required/><input name="maxUses" type="number" placeholder="Limite de usos"/><button>Criar cupom</button></form><div className="adminTable"><h2>Cupons</h2>{coupons.map(c=><div className="adminCouponRow" key={c.id}><b>{c.code}</b><span>{c.type==='percent'?c.value+'%':money(c.value)}</span><span>{c.used_count||0}/{c.max_uses||'∞'}</span><em>{c.active?'Ativo':'Inativo'}</em></div>)}</div></>}
 </section></main>
}