'use client'; import {useState} from 'react';
const products=[
{name:'Bigode Basic',price:39.90,tag:'ESSENCIAL',desc:'Plano de entrada com acesso rápido e suporte.'},
{name:'Bigode Advanced',price:69.90,tag:'POPULAR',desc:'Recursos avançados e prioridade no atendimento.'},
{name:'Bigode Premium',price:99.90,tag:'PREMIUM',desc:'Pacote completo para quem quer mais recursos.'},
{name:'Bigode Ultimate',price:149.90,tag:'ULTIMATE',desc:'A experiência Bigode mais completa.'}];
export default function Home(){const [cart,setCart]=useState([]);const [open,setOpen]=useState(false);const total=cart.reduce((a,p)=>a+p.price,0);return <main>
<div className="notice">SUPORTE RÁPIDO • ENTREGA DIGITAL • AMBIENTE SEGURO</div>
<header><a className="logo" href="#"><span>BIGODE</span> BYPASS</a><nav><a href="#produtos">Produtos</a><a href="#vantagens">Vantagens</a><a href="#faq">FAQ</a></nav><button className="cart" onClick={()=>setOpen(true)}>Carrinho <b>{cart.length}</b></button></header>
<section className="hero"><div><div className="eyebrow">BIGODE STORE</div><h1>O próximo nível<br/><em>começa aqui.</em></h1><p>Produtos digitais em uma experiência rápida, direta e feita para desktop.</p><a className="primary" href="#produtos">Ver produtos →</a></div><div className="orb"><div className="mustache">⌁</div><strong>BIGODE</strong><small>BYPASS</small></div></section>
<section className="stats"><div><b>24/7</b><span>Loja online</span></div><div><b>100%</b><span>Entrega digital</span></div><div><b>4</b><span>Planos Bigode</span></div><div><b>PC</b><span>Experiência otimizada</span></div></section>
<section id="produtos" className="section"><div className="sectionHead"><div><span>NOSSOS PRODUTOS</span><h2>Escolha seu Bigode</h2></div><p>Do essencial ao pacote mais completo.</p></div><div className="grid">{products.map((p,i)=><article className={'card '+(i===1?'featured':'')} key={p.name}><div className="tag">{p.tag}</div><div className="icon">B</div><h3>{p.name}</h3><p>{p.desc}</p><ul><li>Entrega digital</li><li>Acesso à área do cliente</li><li>Suporte especializado</li></ul><div className="price"><small>a partir de</small><b>R$ {p.price.toFixed(2).replace('.',',')}</b></div><button onClick={()=>{setCart([...cart,p]);setOpen(true)}}>Adicionar ao carrinho</button></article>)}</div></section>
<section id="vantagens" className="benefits"><div><span>01</span><h3>Entrega digital</h3><p>Pedido organizado na sua conta após confirmação.</p></div><div><span>02</span><h3>Área do cliente</h3><p>Acompanhe pedidos e seus produtos em um só lugar.</p></div><div><span>03</span><h3>Suporte</h3><p>Central de ajuda para dúvidas sobre sua compra.</p></div></section>
<section id="faq" className="faq"><span>DÚVIDAS FREQUENTES</span><h2>FAQ</h2><details><summary>Como recebo meu produto?</summary><p>Produtos digitais ficam disponíveis conforme as instruções do pedido após a confirmação do pagamento.</p></details><details><summary>Quais formas de pagamento?</summary><p>O checkout está preparado para integração com um provedor de pagamentos. As credenciais serão configuradas antes da publicação comercial.</p></details><details><summary>Consigo acompanhar meu pedido?</summary><p>Sim. A versão com backend terá conta do cliente e histórico de pedidos.</p></details></section>
<footer><div className="logo"><span>BIGODE</span> BYPASS</div><p>© 2026 Bigode Bypass. Todos os direitos reservados.</p><div>Termos • Privacidade • Suporte</div></footer>
{open&&<div className="overlay" onClick={()=>setOpen(false)}><aside onClick={e=>e.stopPropagation()}><button className="x" onClick={()=>setOpen(false)}>×</button><h2>Seu carrinho</h2>{!cart.length?<p className="empty">Seu carrinho está vazio.</p>:cart.map((p,i)=><div className="cartItem" key={i}><span>{p.name}</span><b>R$ {p.price.toFixed(2).replace('.',',')}</b><button onClick={()=>setCart(cart.filter((_,j)=>j!==i))}>remover</button></div>)}<div className="total"><span>Total</span><b>R$ {total.toFixed(2).replace('.',',')}</b></div><button className="checkout" disabled={!cart.length}>Continuar para checkout</button><small>Checkout real será ativado após configurar banco e provedor de pagamento.</small></aside></div>}</main>}