'use client';import{useMemo,useState}from'react';
const products=[
{name:'Bigode Basic',old:70,price:50,tag:'BASIC',tone:'green'},
{name:'Bigode Advanced',old:200,price:150,tag:'ADVANCED',tone:'purple'},
{name:'Bigode Premium',old:300,price:250,tag:'PREMIUM',tone:'pink'},
{name:'Bigode Ultimate',old:450,price:400,tag:'ULTIMATE',tone:'cyan'},
{name:'Bigode Remote',old:700,price:500,tag:'REMOTE',tone:'blue'},
{name:'Bigode Exclusive',old:750,price:600,tag:'EXCLUSIVE',tone:'orange'},
{name:'Bigode Pro',old:950,price:750,tag:'PRO',tone:'violet'},
{name:'Bigode 1:1',old:1500,price:1300,tag:'1:1',tone:'blue'}];
const money=n=>'R$ '+n.toFixed(2).replace('.',',');
export default function Home(){const[cart,setCart]=useState([]),[drawer,setDrawer]=useState(false),[query,setQuery]=useState(''),[profile,setProfile]=useState(false);const shown=products.filter(p=>p.name.toLowerCase().includes(query.toLowerCase()));const total=useMemo(()=>cart.reduce((a,p)=>a+p.price,0),[cart]);return <main>
<div className="support">Alguma dúvida? <b>Abra um ticket em nosso servidor</b></div>
<header><a className="brand" href="#"><div className="miniLogo">〰</div><div><strong>Bigode Bypass</strong><small>LOJA DIGITAL</small></div><i>✓</i></a><div className="search">⌕<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar produto"/></div><div className="actions"><button className="headset">◉</button><div className="profileWrap"><button className="profile" onClick={()=>setProfile(!profile)}><span>BB</span><div><b>Cliente</b><small>Meu perfil⌄</small></div></button>{profile&&<div className="profileMenu"><b>Minha conta</b><small>cliente@bigode.com</small><hr/><a href="/pedidos">▣ Meus pedidos</a><button className="logout">↪ Sair da conta</button></div>}</div><button className="cartBtn" onClick={()=>setDrawer(true)}>🛒 Carrinho <b>{cart.length}</b></button></div></header>
<section className="banner"><div className="bigMustache">〰</div><div className="bannerWords"><strong>BIGODE</strong><span>BYPASS</span></div></section>
<section className="intro"><h1>A <em>Nº 1</em> em experiência<br/>de produtos digitais.</h1><p>Uma loja moderna, rápida e organizada, com atendimento eficiente e uma experiência de compra feita para PC.</p><a href="#produtos">Ver produtos　→</a></section>
<section className="popular"><h2>Categorias populares</h2><div className="category"><div className="catArt">〰<b>BIGODE</b></div><strong>BIGODE</strong></div></section>
<section id="produtos" className="catalog"><aside className="filters"><b>PRODUTOS</b><button className="active">BIGODE</button><button>DESTAQUES</button></aside><div className="productArea"><div className="tab">BIGODE</div><div className="products">{shown.map(p=><article className={'product '+p.tone} key={p.name}><div className="productArt"><div>〰</div><strong>{p.tag}</strong><small>BIGODE BYPASS</small></div><div className="productBody"><h3>{p.name}</h3><div className="deal"><s>{money(p.old)}</s><span>⌁ {Math.round((1-p.price/p.old)*100)}% OFF</span></div><b className="amount">{money(p.price)}</b><small>À vista no Pix</small><button onClick={()=>{setCart([...cart,p]);setDrawer(true)}}>🛒　Comprar agora</button></div></article>)}</div></div></section>
<section className="why"><div><b>⚡ Entrega digital</b><span>Processo rápido e organizado.</span></div><div><b>🔒 Compra segura</b><span>Checkout preparado para pagamento protegido.</span></div><div><b>🎧 Suporte</b><span>Atendimento para suas compras.</span></div></section>
<footer><div><div className="brand foot"><div className="miniLogo">〰</div><strong>Bigode Bypass</strong></div><p>Produtos digitais com uma experiência rápida e suporte eficiente.</p></div><div className="social">◉　▶　♪</div><div className="copy">Copyright © 2026 - Bigode Bypass.</div><div className="links">Termos e condições　 Privacidade</div></footer>
{drawer&&<div className="shade" onClick={()=>setDrawer(false)}><aside className="drawer" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setDrawer(false)}>×</button><h2>Carrinho</h2>{cart.length===0?<p className="empty">Seu carrinho está vazio.</p>:cart.map((p,i)=><div className="cartLine" key={i}><div><b>{p.name}</b><small>Produto digital</small></div><strong>{money(p.price)}</strong><button onClick={()=>setCart(cart.filter((_,j)=>j!==i))}>×</button></div>)}<div className="sum"><span>Total</span><b>{money(total)}</b></div><a className={"go "+(!cart.length?"disabled":"")} href={cart.length?"/checkout":"#"}>Ir para checkout</a><small className="safe">🔒 Ambiente de compra protegido</small></aside></div>}</main>}