'use client';
import{useEffect,useMemo,useState}from'react';
import{api}from'../../lib/api-client';
import{loadSite,defaultSite}from'../../lib/site-client';
import{cartTotal,clearCart,loadCart}from'../../lib/cart-client';
import{trackEvent,trackPageView}from'../../lib/analytics';
const money=v=>'R$ '+Number(v||0).toFixed(2).replace('.',',');
export default function Checkout(){
  const[cart,setCart]=useState([]),[user,setUser]=useState(null),[name,setName]=useState(''),[email,setEmail]=useState(''),[cpf,setCpf]=useState(''),[coupon,setCoupon]=useState(''),[discount,setDiscount]=useState(0),[message,setMessage]=useState(''),[loading,setLoading]=useState(false),[done,setDone]=useState(null),[site,setSite]=useState(defaultSite);
  useEffect(()=>{trackPageView({source:'checkout'});setCart(loadCart());loadSite().then(setSite);api('/auth/me').then(d=>{setUser(d.user);setName(d.user.name||'');setEmail(d.user.email||'');setCpf(d.user.cpf||'')}).catch(()=>{})},[]);
  const subtotal=useMemo(()=>cartTotal(cart),[cart]),total=Math.max(0,subtotal-discount);
  const validate=async()=>{trackEvent('coupon_attempt',{code:coupon.slice(0,30)});try{const d=await api('/coupons/validate',{method:'POST',body:JSON.stringify({code:coupon,subtotal})});setDiscount(d.valid?Number(d.discount):0);setMessage(d.valid?'Cupom aplicado.':'Cupom inválido ou expirado.')}catch(e){setMessage(e.message)}};
  const order=async()=>{if(!cart.length)return; if(!name||!email){setMessage('Preencha nome e e-mail.');return}trackEvent('checkout_submit',{cartCount:cart.reduce((s,x)=>s+(x.quantity||1),0),cartTotal:total,method:'pix'});setLoading(true);setMessage('');try{const d=await api('/orders',{method:'POST',body:JSON.stringify({customerName:name,customerEmail:email,cpf,items:cart.map(x=>({slug:x.slug,quantity:x.quantity||1})),couponCode:coupon,paymentMethod:'pix'})});trackEvent('checkout_submit',{status:'created',orderId:d.order?.id,cartTotal:Number(d.order?.total||total),method:'pix'});clearCart();setDone(d.order);setCart([])}catch(e){setMessage(e.message)}finally{setLoading(false)}};
  if(done)return <main className="checkoutPage" style={{'--blue':site.primaryColor,'--bg':site.backgroundColor,'--panel':site.panelColor}}><div className="checkoutBox success"><img className="successLogo" src={site.logoUrl} alt=""/><h1>Pedido #{done.id} criado ✓</h1><p>O pedido foi registrado como <b>pendente</b>. O Pix real será ativado quando o provedor de pagamento for conectado.</p><b className="successTotal">{money(done.total)}</b>{user&&<a href="/pedidos">Ver meus pedidos</a>}<a href="/">Voltar à loja</a></div></main>;
  return <main className="checkoutPage" style={{'--blue':site.primaryColor,'--bg':site.backgroundColor,'--panel':site.panelColor}}><div className="checkoutBrand"><img src={site.logoUrl} alt={site.siteName}/><b>{site.siteName}</b></div><a className="back" href="/">← Voltar para a loja</a><div className="checkoutGrid"><section className="checkoutBox"><span>FINALIZAR COMPRA</span><h1>Checkout</h1>{!user&&<p className="checkoutHint">Já possui conta? <a href="/conta">Entrar</a> para acompanhar o pedido.</p>}<label>Nome completo<input maxLength="100" value={name} onChange={e=>setName(e.target.value)} placeholder="Seu nome"/></label><label>E-mail<input type="email" maxLength="120" value={email} onChange={e=>setEmail(e.target.value)} placeholder="seu@email.com"/></label><label>CPF<input inputMode="numeric" maxLength="14" value={cpf} onChange={e=>setCpf(e.target.value)} placeholder="000.000.000-00"/></label><label>Cupom<div className="coupon"><input maxLength="30" value={coupon} onChange={e=>setCoupon(e.target.value.toUpperCase())} placeholder="Código do cupom"/><button type="button" onClick={validate}>Aplicar</button></div></label>{message&&<p className="formMessage">{message}</p>}<h3>Forma de pagamento</h3><button className="pix" type="button">◆ PIX <small>Integração preparada</small></button></section><aside className="checkoutBox summary"><h2>Resumo</h2>{cart.map(x=><div className="summaryItem" key={x.slug}><span>{x.name} × {x.quantity||1}</span><b>{money(Number(x.price)*(x.quantity||1))}</b></div>)}{!cart.length&&<p className="empty">Carrinho vazio.</p>}<div><span>Subtotal</span><b>{money(subtotal)}</b></div><div><span>Desconto</span><b>- {money(discount)}</b></div><hr/><div className="grand"><span>Total</span><b>{money(total)}</b></div><button className="pay" disabled={!cart.length||loading} onClick={order}>{loading?'Criando pedido...':'Criar pedido'}</button><small>🔒 Seus dados são protegidos.</small></aside></div></main>
}